name: CI
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: enabled
      ENT_USERNAME: ${{ secrets.ENT_USERNAME }}
      ENT_PASSWORD: ${{ secrets.ENT_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install pipenv
        run: pip3 install pipenv
      - name: Install dependencies
        run: pipenv install
      - name: Start remote browser
        run: docker-compose up -d
      - name: Wait browser to be up
        run: until curl -I localhost:4444; do sleep 1; done
      - name: Prepare environment
        run: cp .env.example .env
      - name: Scraps and parse
        run: pipenv run python main.py
      - name: Stop the browser remote
        run: docker-compose down
